version: 2

models:
  # Marts
  ## fct_customers_orders
  - name: fct_customer_orders
    description: Contains the full information about the orders per customer. 
    columns:
      - name: order_id
        description: Primary key for orders.
        tests:
          - unique
          - not_null
      - name: customer_id
        description: Foreign key to stg_customers.customer_id.
        tests:
          - not_null
          - relationships:
              field: customer_id
              to: ref('stg_customers')
      - name: order_placed_at
        description: Date of the order (YYY-MM-DD)  
      - name: order_status
        description: '{{ doc("order_status") }}'
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
      - name: total_amount_paid
        description: Payment amount in dollars. Single can be negative if refund.    
      - name: payment_finalized_date
        description: Date of the transaction (YYY-MM-DD).
      - name: customer_first_name
        description: First name of the customer.
      - name: customer_last_name
        description: Initial of customer's last name.
      - name: transaction_seq
        description: Sequence number of the overall transactions.
      - name: customer_sales_seq
        description: Sequence number of each sales per customer.
      - name: nvsr
        description: New vs Return customer - if the customer has more than one order, it will be marked as return.
      - name: customer_lifetime_value
        description: Sum of all the orders amount per customer up until the payment_finalized_date.
      - name: fdos
        description: First date of sales per customer.


  ## int_orders
  - name: int_orders
    description: Contain the amount of each order per customer with temporal information.
    columns:
      - name: order_id
        description: Primary key for orders.
        tests:
          - unique
          - not_null
      - name: customer_id
        description: Foreign key to stg_customers.customer_id.
        tests:
          - not_null
          - relationships:
              field: customer_id
              to: ref('stg_customers')
      - name: order_placed_at
        description: Date of the order (YYY-MM-DD)  
      - name: order_status
        description: '{{ doc("order_status") }}'
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
      - name: total_amount_paid
        description: Payment amount in dollars. Single can be negative if refund.    
      - name: payment_finalized_date
        description: Date of the transaction (YYY-MM-DD).



  # Staging
  ## stg_customers
  - name: stg_customers
    description: Staged customer data from our jaffle shop app. This model cleans up customer data.
    columns:
      - name: customer_id
        description: Primary key for customers.
        tests:
          - unique
          - not_null
      - name: first_name
        description: First name of the customer.
      - name: last_name
        description: Initial of customer's last name.

  ## stg_orders
  - name: stg_orders
    description: Staged order data from our jaffle shop app. This model cleans up order data.
    columns:
      - name: order_id
        description: Primary key for orders.
        tests:
          - unique
          - not_null
      - name: customer_id
        description: Foreign key to stg_customers.customer_id.
        tests:
          - not_null
          - relationships:
              field: customer_id
              to: ref('stg_customers')
      - name: order_date
        description: Date of the order (YYY-MM-DD).
      - name: status
        description: '{{ doc("order_status") }}'
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
      - name: valid_order_date 
        description: Marks the order_placed_at if order_status NOT IN ('returned', 'return_pending'), else NULL.

  ## stg_payments
  - name: stg_payments
    description: Staged payment data from our stripe app. This model cleans up payment data.
    columns:
      - name: payment_id
        description: Primary key for the payments.
        tests:
          - unique
          - not_null
      - name: order_id
        description: Foreign key to stg_orders.order_id
        tests:
          - not_null
          - relationships:
              field: order_id
              to: ref('stg_orders')
      - name: payment_method
        description: '{{ doc("payment_method") }}'
        tests:
          - accepted_values:
              values: ['credit_card', 'bank_transfer', 'coupon', 'gift_card']
      - name: status
        description: '{{ doc("payment_status") }}'
        tests:
          - accepted_values:
              values: ['success', 'fail']
      - name: amount
        description: Payment amount in dollars. Single can be negative if refund.
      - name: created_at
        description: Date of the transaction (YYY-MM-DD).

      

