version: 2

sources:
  - name: jaffle_shop
    description: A clone of a Postgres application database.
    database: 'dbt-tutorial'
    # schema: jaffle_shop
    tables:
      - name: customers
        description: The raw customers data.
        columns:
          - name: id
            description: Primary key of the raw customer data.
            tests:
              - unique
              - not_null
          - name: first_name
            description: First name of the customer.
          - name: last_name
            description: Initial of customer's last name.

      - name: orders
        description: The raw orders data.
        columns:
          - name: id
            description: Primary key of the raw orders data.
            tests:
              - unique
              - not_null
          - name: order_date
            description: Date of the order (YYY-MM-DD).
          - name: status
            description: '{{ doc("order_status") }}'
            tests:
              - accepted_values:
                  values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
          - name: user_id
            description: Foreign key to customers.id.
            tests:
              - not_null
              - relationships:
                  field: id
                  to: ref('customers')
        loaded_at_field: _etl_loaded_at
        freshness: 
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
        
  # stripe
  - name: stripe
    description: A clone of a Postgres application database.
    database: 'dbt-tutorial'
    # schema: stripe
    tables:
      - name: payment
        description: The raw payments data.
        columns:
          - name: id
            description: Primary key of the raw payment data.
            tests:
              - unique
              - not_null
          - name: orderid
            description: Foreign key to orders.id
            tests:
              - not_null
              - relationships:
                  field: id
                  to: ref('orders')
          - name: paymentmethod
            description: '{{ doc("payment_method") }}'
            tests:
              - accepted_values:
                  values: ['credit_card', 'bank_transfer', 'coupon', 'gift_card']
          - name: status
            description: '{{ doc("payment_status") }}'
            tests:
              - accepted_values:
                  values: ['success', 'fail']
          - name: amount
            description: Payment amount in cents. Can be negative if refund.
          - name: created
            description: Date of the transaction (YYY-MM-DD).
        loaded_at_field: _batched_at
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
  
  